import { listChannelPlugins } from "../channels/core/plugins/index.js";

const BASE_METHODS = [
  "health",
  "logs.tail",
  "channels.status",
  "channels.logout",
  "status",
  "usage.status",
  "usage.cost",
  "tts.status",
  "tts.providers",
  "tts.enable",
  "tts.disable",
  "tts.convert",
  "tts.setProvider",
  "config.get",
  "config.set",
  "config.apply",
  "config.patch",
  "config.schema",
  "exec.approvals.get",
  "exec.approvals.set",
  "exec.approvals.node.get",
  "exec.approvals.node.set",
  "exec.approval.request",
  "exec.approval.resolve",
  "wizard.start",
  "wizard.next",
  "wizard.cancel",
  "wizard.status",
  "talk.mode",
  "models.list",
  "agents.list",
  "skills.status",
  "skills.bins",
  "skills.install",
  "skills.update",
  "update.run",
  "voicewake.get",
  "voicewake.set",
  "sessions.list",
  "sessions.preview",
  "sessions.patch",
  "sessions.reset",
  "sessions.delete",
  "sessions.compact",
  "last-heartbeat",
  "set-heartbeats",
  "wake",
  "node.pair.request",
  "node.pair.list",
  "node.pair.approve",
  "node.pair.reject",
  "node.pair.verify",
  "device.pair.list",
  "device.pair.approve",
  "device.pair.reject",
  "device.token.rotate",
  "device.token.revoke",
  "node.rename",
  "node.list",
  "node.describe",
  "node.invoke",
  "node.invoke.result",
  "node.event",
  "cron.list",
  "cron.status",
  "cron.add",
  "cron.update",
  "cron.remove",
  "cron.run",
  "cron.runs",
  "system-presence",
  "system-event",
  "send",
  "agent",
  "agent.identity.get",
  "agent.wait",
  "browser.request",
  // WebChat WebSocket-native chat methods
  "chat.history",
  "chat.abort",
  "chat.send",
  // Windows Assistant methods
  "assistant.info",
  "assistant.chat",
  "assistant.confirm.request",
  "assistant.confirm.response",
  "assistant.capabilities",
  "assistant.heartbeat",
  "assistant.command.execute",
  "assistant.command.result",
  // Assistant skill system methods
  "assistant.skills.list",
  "assistant.skills.get",
  "assistant.skills.execute",
  "assistant.skills.executeByCommand",
  "assistant.skills.tools",
  "assistant.skills.reload",
  "assistant.skills.findByCommand",
  "assistant.skills.install",
  "assistant.skills.uninstall",
  "assistant.skills.enable",
  "assistant.skills.disable",
  "assistant.skills.toggle",
  "assistant.skills.getConfig",
  "assistant.skills.setConfig",
  "assistant.skills.stats",
  "assistant.skills.listAll",
  // Assistant skill store methods
  "assistant.store.query",
  "assistant.store.detail",
  "assistant.store.featured",
  "assistant.store.popular",
  "assistant.store.recent",
  "assistant.store.stats",
  "assistant.store.search",
  "assistant.store.checkUpdates",
  "assistant.store.refresh",
  "assistant.store.install",
  // Assistant audit methods
  "assistant.audit.init",
  "assistant.audit.write",
  "assistant.audit.query",
  "assistant.audit.recent",
  "assistant.audit.stats",
  "assistant.audit.export",
  "assistant.audit.clear",
  "assistant.audit.config.get",
  "assistant.audit.config.set",
  // Assistant subscription methods
  "assistant.subscription.plans",
  "assistant.subscription.plan",
  "assistant.subscription.get",
  "assistant.subscription.create",
  "assistant.subscription.update",
  "assistant.subscription.cancel",
  "assistant.subscription.quota.check",
  "assistant.subscription.usage",
  "assistant.subscription.usage.record",
  "assistant.subscription.overview",
  // User authentication methods
  "auth.sendCode",
  "auth.register",
  "auth.login",
  "auth.refreshToken",
  "auth.logout",
  "auth.logoutAll",
  // Data migration methods
  "migration.start",
  "migration.status",
  "migration.verify",
  "migration.updateConfig",
  "migration.getConfig",
  "migration.dualWrite.init",
  "migration.dualWrite.setMode",
  "migration.dualWrite.setReadStrategy",
  "migration.dualWrite.getStats",
  "migration.dualWrite.resetStats",
  "migration.dualWrite.getConfig",
  "migration.rollback.preview",
  "migration.rollback.execute",
  "migration.rollback.status",
  // Payment methods
  "payment.createOrder",
  "payment.getOrder",
  "payment.queryOrders",
  "payment.cancelOrder",
  "payment.initiatePayment",
  "payment.getPaymentStatus",
  "payment.requestRefund",
  "payment.getRefundStatus",
  "payment.getUserPayments",
  "payment.getRecentTransactions",
  "payment.estimatePrice",
  "payment.getSupportedProviders",
  // Coupon methods
  "coupon.validate",
  "coupon.apply",
  "coupon.create",
  "coupon.list",
  "coupon.get",
  "coupon.update",
  "coupon.disable",
  "coupon.getUserUsages",
  // Auto renewal methods
  "renewal.getTasks",
  "renewal.getTask",
  "renewal.trigger",
  "renewal.cancel",
  "renewal.updateConfig",
  "renewal.getConfig",
  "renewal.start",
  "renewal.stop",
  // Admin console authentication methods
  "admin.login",
  "admin.refreshToken",
  "admin.logout",
  "admin.logoutAll",
  "admin.getProfile",
  "admin.validateToken",
  // Admin console user management methods
  "admin.users.list",
  "admin.users.get",
  "admin.users.suspend",
  "admin.users.activate",
  "admin.users.resetPassword",
  "admin.users.unlinkDevice",
  "admin.users.forceLogout",
  "admin.users.stats",
  // Admin console subscription management methods
  "admin.subscriptions.list",
  "admin.subscriptions.get",
  "admin.subscriptions.cancel",
  "admin.subscriptions.extend",
  "admin.subscriptions.changePlan",
  "admin.subscriptions.stats",
  // Admin console plan management methods
  "admin.plans.list",
  "admin.plans.get",
  "admin.plans.create",
  "admin.plans.update",
  // Admin console order management methods
  "admin.orders.list",
  "admin.orders.get",
  "admin.orders.refund",
  // Admin console audit log methods
  "admin.auditLogs.list",
  "admin.auditLogs.get",
  "admin.auditLogs.stats",
  "admin.auditLogs.actionTypes",
  "admin.auditLogs.export",
  "admin.auditLogs.admins",
  // Admin console dashboard methods
  "admin.dashboard.stats",
  "admin.dashboard.trends",
  "admin.dashboard.subscriptionDistribution",
  "admin.dashboard.activities",
  // Admin console skill management methods
  "admin.skills.stats",
  "admin.skills.list",
  "admin.skills.get",
  "admin.skills.review",
  "admin.skills.publish",
  "admin.skills.setFeatured",
  "admin.skills.categories.list",
  "admin.skills.categories.create",
  "admin.skills.categories.update",
  "admin.skills.categories.delete",
  "admin.skills.featured.list",
  "admin.skills.featured.reorder",
  // Admin console system monitoring methods
  "admin.monitor.stats",
  "admin.monitor.health",
  "admin.monitor.api",
  "admin.monitor.resources",
  "admin.monitor.resources.history",
  "admin.monitor.logs",
  "admin.monitor.logs.sources",
  "admin.monitor.alerts",
  "admin.monitor.alerts.acknowledge",
  "admin.monitor.alerts.resolve",
  // Admin console system configuration methods
  "admin.config.site.get",
  "admin.config.site.set",
  "admin.config.features.get",
  "admin.config.features.set",
  "admin.config.security.get",
  "admin.config.security.set",
  "admin.config.notifications.list",
  "admin.config.notifications.get",
  "admin.config.notifications.update",
  "admin.config.notifications.test",
  "admin.config.all",
  // Admin console data analytics methods
  "admin.analytics.overview",
  "admin.analytics.users.growth",
  "admin.analytics.users.retention",
  "admin.analytics.users.demographics",
  "admin.analytics.revenue.trend",
  "admin.analytics.revenue.sources",
  "admin.analytics.revenue.metrics",
  "admin.analytics.skills.usage",
  "admin.analytics.funnels.list",
  "admin.analytics.funnels.get",
];

export function listGatewayMethods(): string[] {
  const channelMethods = listChannelPlugins().flatMap((plugin) => plugin.gatewayMethods ?? []);
  return Array.from(new Set([...BASE_METHODS, ...channelMethods]));
}

export const GATEWAY_EVENTS = [
  "connect.challenge",
  "agent",
  "chat",
  "presence",
  "tick",
  "talk.mode",
  "shutdown",
  "health",
  "heartbeat",
  "cron",
  "node.pair.requested",
  "node.pair.resolved",
  "node.invoke.request",
  "device.pair.requested",
  "device.pair.resolved",
  "voicewake.changed",
  "exec.approval.requested",
  "exec.approval.resolved",
  // Windows Assistant events
  "confirm.request",
  "assistant.notification",
  "command.execute.request",
];
