export const browserCoreExamples = [
  "mtbot browser status",
  "mtbot browser start",
  "mtbot browser stop",
  "mtbot browser tabs",
  "mtbot browser open https://example.com",
  "mtbot browser focus abcd1234",
  "mtbot browser close abcd1234",
  "mtbot browser screenshot",
  "mtbot browser screenshot --full-page",
  "mtbot browser screenshot --ref 12",
  "mtbot browser snapshot",
  "mtbot browser snapshot --format aria --limit 200",
  "mtbot browser snapshot --efficient",
  "mtbot browser snapshot --labels",
];

export const browserActionExamples = [
  "mtbot browser navigate https://example.com",
  "mtbot browser resize 1280 720",
  "mtbot browser click 12 --double",
  'mtbot browser type 23 "hello" --submit',
  "mtbot browser press Enter",
  "mtbot browser hover 44",
  "mtbot browser drag 10 11",
  "mtbot browser select 9 OptionA OptionB",
  "mtbot browser upload /tmp/file.pdf",
  'mtbot browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "mtbot browser dialog --accept",
  'mtbot browser wait --text "Done"',
  "mtbot browser evaluate --fn '(el) => el.textContent' --ref 7",
  "mtbot browser console --level error",
  "mtbot browser pdf",
];
